# =============================================================================
# config.jl — Central path configuration for the SisgeSC pipeline
# =============================================================================
# Set BASE_DIR to the root of your project directory before running any script.
# All data paths are defined relative to this directory.
#
# Usage:
#   include("config.jl")
#
# Then use the path constants (e.g., PATH_RAW_CNEFE, PATH_OUTPUT_STAGE1, etc.)
# in your scripts instead of hardcoded absolute paths.
# =============================================================================

# ── Root directory ───────────────────────────────────────────────────────────
# Change this single line to match your local setup.
const BASE_DIR = @__DIR__

# ── Raw IBGE data (user must download; see data/README.md) ───────────────────
const PATH_RAW       = joinpath(BASE_DIR, "data", "raw")
const PATH_RAW_CNEFE = joinpath(PATH_RAW, "cnefe")          # CNEFE CSV (42_SC.csv)
const PATH_RAW_AGGR  = joinpath(PATH_RAW, "aggregates")     # Census aggregates by tract
const PATH_RAW_SIDRA = joinpath(PATH_RAW, "sidra")          # SIDRA tables (population, families)
const PATH_RAW_MICRO = joinpath(PATH_RAW, "microdata_2010") # 2010 Census microdata sample
const PATH_RAW_POP25 = joinpath(PATH_RAW, "pop_estimates")  # IBGE 2025 population estimates

# ── Intermediate outputs (generated by the pipeline) ─────────────────────────
const PATH_STAGE1 = joinpath(BASE_DIR, "output", "stage1_residences")
const PATH_STAGE2 = joinpath(BASE_DIR, "output", "stage2_attributes")
const PATH_STAGE3 = joinpath(BASE_DIR, "output", "stage3_population")
const PATH_STAGE4 = joinpath(BASE_DIR, "output", "stage4_update_2025")

# ── Final results ────────────────────────────────────────────────────────────
const PATH_RESULTS = joinpath(BASE_DIR, "output", "results")

# ── Create output directories if they don't exist ────────────────────────────
for p in [PATH_STAGE1, PATH_STAGE2, PATH_STAGE3, PATH_STAGE4,
          PATH_RESULTS]
    mkpath(p)
end
